### ISSUE TITLE
Are you sure it's gonna work?

### ISSUE THREAD

**Issue by Lucifer192192** [Memisz/Twitch-Viewbot#1]
There's only one head. I don't think that's possible

**Comment by Galletitaguapa** [comment]
Pygradient is not a valid module

**Comment by Munhrar** [comment]
are working with someone, because with me, give this errors.


![Twitch Viewbot](https://user-images.githubusercontent.com/47261538/196033295-6f501dfa-8851-4c32-9f98-c91ab0a5859f.jpg)

**Comment by thehackedone** [comment]
If you look it up google tells me pygradient is a malicious package....
